name: Unit Tests

on:
  push:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    env:
      MONGODB_URL: ${{ secrets.MONGODB_URL }}
      LOCAL_MONGODB_URL: ${{ secrets.LOCAL_MONGODB_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      # - name: Run tests
      #   run: npm test
      
      - name: Use Python 
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Python dependencies and Robot Framework
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade robotframework robotframework-seleniumlibrary

      - name: Run Robot tests
        run: |
          cd tests
          robot --exclude resource .
      
  deploy:
    name: Deploy
    needs: [tests]
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          KEY: ${{ secrets.KEY}}
          PORT: $${{ secrets.PORT}}
          service-id: ${{ secrets.SERVICE_ID}}
          api-key: ${{ secrets.RENDER_API_KEY}}
