name: Unit Tests

on:
  push:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    env:
      MONGODB_URL: ${{ secrets.MONGODB_URL }}
      LOCAL_MONGODB_URL: ${{ secrets.LOCAL_MONGODB_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  deploy:
      name: Deploy
      needs: [tests]
      runs-on: ubuntu-latest

      steps:
        - name: Clear Cache
          run: npm cache clean --force
        - name: Deploy to production
          uses: johnbeynon/render-deploy-action@v0.0.8
          with:
            service-id: ${{ secrets.SERVICE_ID}}
            api-key: ${{ secrets.RENDER_API_KEY}}
            clearCache: "clear"

